package vista;

import java.awt.Dimension;
import vista.utilitario.Utilitario;

/**
 *
 * @author Encalada Maria
 */
public class FrmPersonalRegistrado extends javax.swing.JDialog {
    Utilitario u= new Utilitario();

    /**
     * Creates new form FrmPersonalRegistrado
     */
    public FrmPersonalRegistrado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPR = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSalir = new org.edisoncor.gui.button.ButtonAction();
        btnGuardar = new org.edisoncor.gui.button.ButtonAction();
        btnCancelar = new org.edisoncor.gui.button.ButtonAction();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        txtBuscar = new org.edisoncor.gui.textField.TextFieldRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Casa Financiera \"Doña Bachita\"");
        setIconImage(u.getIconImage());
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlPR.setBackground(new java.awt.Color(0, 0, 51));
        pnlPR.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Cedula", "Correo Electronico", "Direccion", "Telefono"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        pnlPR.add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 600, 270);

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de Personal");
        pnlPR.add(jLabel1);
        jLabel1.setBounds(150, 10, 220, 40);

        btnSalir.setText("salir");
        pnlPR.add(btnSalir);
        btnSalir.setBounds(480, 440, 116, 35);

        btnGuardar.setText("Guardar Cambios");
        pnlPR.add(btnGuardar);
        btnGuardar.setBounds(330, 440, 130, 35);

        btnCancelar.setText("Cancelar Cambios");
        pnlPR.add(btnCancelar);
        btnCancelar.setBounds(166, 440, 140, 35);

        labelMetric1.setBackground(new java.awt.Color(0, 0, 153));
        labelMetric1.setForeground(new java.awt.Color(204, 204, 255));
        labelMetric1.setText("Buscar");
        pnlPR.add(labelMetric1);
        labelMetric1.setBounds(50, 70, 70, 30);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        pnlPR.add(txtBuscar);
        txtBuscar.setBounds(150, 70, 320, 40);

        getContentPane().add(pnlPR);
        pnlPR.setBounds(0, 0, 620, 500);

        setSize(new java.awt.Dimension(634, 541));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        System.out.println("Hola");
        Dimension pantallaTamaño = this.getSize();
        pnlPR.setLocation((pantallaTamaño.width / 2) - (pnlPR.getWidth()) / 2,
                (pantallaTamaño.height / 2) - (pnlPR.getHeight() / 2));
        System.out.println(pantallaTamaño.height + " " + pantallaTamaño.width);
    }//GEN-LAST:event_formWindowStateChanged

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        u.valiarSoloLetras(txtBuscar);
    }//GEN-LAST:event_txtBuscarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalRegistrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPersonalRegistrado dialog = new FrmPersonalRegistrado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction btnCancelar;
    private org.edisoncor.gui.button.ButtonAction btnGuardar;
    private org.edisoncor.gui.button.ButtonAction btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private javax.swing.JPanel pnlPR;
    private org.edisoncor.gui.textField.TextFieldRound txtBuscar;
    // End of variables declaration//GEN-END:variables
}
