/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.utilidades.Utilitario;

/**
 *
 * @author Usuario
 */
public class FrmAdministradorPrincipal extends javax.swing.JFrame {

    Utilitario u = new Utilitario();

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministradorPrincipal() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        rSButton1 = new rojeru_san.RSButton();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        rSButton2 = new rojeru_san.RSButton();
        rSPanelShadow4 = new rojeru_san.RSPanelShadow();
        rSButton4 = new rojeru_san.RSButton();
        rSPanelShadow3 = new rojeru_san.RSPanelShadow();
        rSButton3 = new rojeru_san.RSButton();
        rSPanelShadow5 = new rojeru_san.RSPanelShadow();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Casa Financiera \"Doña Bachita\"");
        setIconImage(u.getIconImage());
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        rSPanelsSlider1.setLayout(null);
        jPanel1.add(rSPanelsSlider1);
        rSPanelsSlider1.setBounds(0, 0, 60, 350);

        rSButton1.setText("Ingresar como cliente");
        rSPanelShadow1.add(rSButton1, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow1);
        rSPanelShadow1.setBounds(70, 130, 300, 60);

        rSButton2.setText("Salir del Sistema");
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        rSPanelShadow2.add(rSButton2, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow2);
        rSPanelShadow2.setBounds(70, 260, 300, 60);

        rSButton4.setText("Ver Historial");
        rSPanelShadow4.add(rSButton4, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow4);
        rSPanelShadow4.setBounds(70, 190, 300, 60);

        rSButton3.setText("Registrar Personal");
        rSButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton3ActionPerformed(evt);
            }
        });
        rSPanelShadow3.add(rSButton3, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow3);
        rSPanelShadow3.setBounds(70, 60, 300, 60);

        rSPanelShadow5.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Bienvenido al Sistema Administrador");
        rSPanelShadow5.add(jLabel1);
        jLabel1.setBounds(10, 0, 310, 50);

        jPanel1.add(rSPanelShadow5);
        rSPanelShadow5.setBounds(60, 0, 320, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 350);

        setSize(new java.awt.Dimension(389, 394));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        new FrmLoging(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton3ActionPerformed
        new FrmAdministradorRegistros(this, true).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministradorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministradorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministradorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministradorPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministradorPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSButton rSButton4;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSPanelShadow rSPanelShadow3;
    private rojeru_san.RSPanelShadow rSPanelShadow4;
    private rojeru_san.RSPanelShadow rSPanelShadow5;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    // End of variables declaration//GEN-END:variables
}
