/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.CuentaServicio;
import controlador.utilidades.Sesion;
import javax.swing.JOptionPane;
import vista.utilidades.Utilitario;

/**
 *
 * @author Usuario
 */
public class FrmLoging extends javax.swing.JDialog {

    Utilitario u = new Utilitario();

    /**
     * Creates new form Loging
     */
    public FrmLoging(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private void inicioSesion() {
        if (!Utilitario.mostrarError(txtUser, "Falta llenar el campo", 'r')
                && !Utilitario.mostrarError(txtPassword, "Falta llenar el campo", 'r')) {
            Sesion.setCuenta(new CuentaServicio().inicioSesion(txtUser.getText(), new String(txtPassword.getPassword())));
            if (Sesion.getCuenta() != null) {
                new FrmAdministradorPrincipal().setVisible(true);
                dispose();
            } else {
                Utilitario.mensajeError("Error", "El usuario o la contraseña no son válidos");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        txtUser = new rojeru_san.RSMTextFull();
        txtPassword = new rojeru_san.RSMPassView();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btn_salir = new rojeru_san.RSButtonRiple();
        btnSesion2 = new rojeru_san.RSButtonRiple();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Casa Financiera \"Doña Bachita\"");
        setIconImage(u.getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelsSlider1.setLayout(null);

        txtUser.setPlaceholder("USUARIO");
        rSPanelsSlider1.add(txtUser);
        txtUser.setBounds(20, 110, 130, 42);

        txtPassword.setPlaceholder("*******");
        rSPanelsSlider1.add(txtPassword);
        txtPassword.setBounds(20, 170, 130, 42);

        jRadioButton1.setBackground(new java.awt.Color(21, 75, 139));
        jRadioButton1.setText("Administrador");
        rSPanelsSlider1.add(jRadioButton1);
        jRadioButton1.setBounds(40, 370, 93, 23);

        jRadioButton2.setBackground(new java.awt.Color(21, 75, 139));
        jRadioButton2.setText("Servicios");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        rSPanelsSlider1.add(jRadioButton2);
        jRadioButton2.setBounds(40, 290, 90, 23);

        jRadioButton3.setBackground(new java.awt.Color(21, 75, 139));
        jRadioButton3.setText("Cajero");
        rSPanelsSlider1.add(jRadioButton3);
        jRadioButton3.setBounds(40, 330, 90, 23);

        jRadioButton4.setBackground(new java.awt.Color(21, 75, 139));
        jRadioButton4.setText("Cliente");
        rSPanelsSlider1.add(jRadioButton4);
        jRadioButton4.setBounds(40, 250, 90, 23);

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.setColorHover(new java.awt.Color(0, 112, 192));
        btn_salir.setColorText(new java.awt.Color(0, 112, 192));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        rSPanelsSlider1.add(btn_salir);
        btn_salir.setBounds(30, 450, 120, 30);

        btnSesion2.setBackground(new java.awt.Color(255, 255, 255));
        btnSesion2.setText("Ingresar");
        btnSesion2.setColorHover(new java.awt.Color(0, 112, 192));
        btnSesion2.setColorText(new java.awt.Color(0, 112, 192));
        btnSesion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesion2ActionPerformed(evt);
            }
        });
        rSPanelsSlider1.add(btnSesion2);
        btnSesion2.setBounds(30, 410, 120, 30);

        getContentPane().add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 500));

        rSPanelShadow1.setBackground(new java.awt.Color(0, 102, 255));
        rSPanelShadow1.setEnabled(false);
        rSPanelShadow1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(21, 75, 139));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Casa financiera \"Doña Bachita\"");
        rSPanelShadow1.add(jLabel1);
        jLabel1.setBounds(220, 20, 340, 60);

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setEnabled(false);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 102, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Casa Financiera \"Doña Bachita\"\nMision\nPrestar servicios de alta calidad para nuestros\nclientes ofreciendo seguridad y confianza con\nsu dinero en nuestras manos.\n\nAgradecemos tu presencia aquí\nDisfruta de nuestros servicios.");
        jScrollPane1.setViewportView(jTextArea1);

        rSPanelShadow1.add(jScrollPane1);
        jScrollPane1.setBounds(200, 260, 390, 190);

        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 500));

        setSize(new java.awt.Dimension(657, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btnSesion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesion2ActionPerformed
        inicioSesion();
    }//GEN-LAST:event_btnSesion2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed
//

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLoging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLoging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLoging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLoging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLoging dialog = new FrmLoging(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnSesion2;
    private rojeru_san.RSButtonRiple btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    private rojeru_san.RSMPassView txtPassword;
    private rojeru_san.RSMTextFull txtUser;
    // End of variables declaration//GEN-END:variables
}
